const DB={
 stages:[{id:'fluid',name:'FLUID',verb:'Connect the Chain',color:'fluid'},{id:'whip',name:'WHIP',verb:'Accelerate the Chain',locked:true},{id:'weapon',name:'WEAPON',verb:'Apply the Chain',locked:true}],
 competencies:[['mobility','Mobility',38],['core','Core',24],['balance','Balance',31],['strength','Strength',22],['flow','Flow',18],['conditioning','Conditioning',28]],
 moves:[
 {id:'breath',name:'360° Breathing + Brace',phase:'ARRIVE',dose:'5 slow breaths',chain:'BREATHE → BRACE',why:'Builds pressure control and trunk awareness.'},
 {id:'root',name:'Supported Root Stance',phase:'ROOT',dose:'3 × 20 sec',chain:'ROOT → ALIGN',why:'Builds foot-to-hip organization without unnecessary tension.'},
 {id:'shift',name:'Supported Weight Shift',phase:'FLUID',dose:'6 / side',chain:'ROOT → SHIFT → RECOVER',why:'Teaches mass transfer while preserving balance.'},
 {id:'bird',name:'Bird Dog',phase:'STRUCTURE',dose:'5 / side',chain:'BRACE → REACH → RESIST',why:'Develops anti-rotation for chained movement.'},
 {id:'sit',name:'Supported Sit-to-Stand',phase:'BUILD',dose:'5 reps',chain:'ROOT → HINGE → DRIVE',why:'Progresses the squat pattern from current capacity.'},
 {id:'flow',name:'Step–Shift–Turn Flow',phase:'FLOW',dose:'3 × 45 sec',chain:'STEP → SHIFT → TURN → RECOVER',why:'Begins continuous locomotion without forced speed.'},
 {id:'walk',name:'Easy Walk',phase:'CONDITION',dose:'8–12 min',chain:'ROOT → LOCOMOTE → BREATHE',why:'Builds gait and aerobic capacity.'},
 {id:'return',name:'Return Sequence',phase:'RETURN',dose:'3 min',chain:'BREATHE → RELEASE → RESET',why:'Downshifts the session and restores easy motion.'}
 ],
 ranges:['OUTSIDE','LOW LINE','LONG','MID','POCKET','CONTACT','REDIRECT','CLINCH','GROUND']
};
const defaults={page:'home',completed:0,sessions:0,flowIndex:0,readiness:'normal'};
let state={...defaults,...JSON.parse(localStorage.getItem('fww-state')||'{}')};
const save=()=>localStorage.setItem('fww-state',JSON.stringify(state));
const nav=()=>`<nav class="nav">${[['home','HOME'],['train','TRAIN'],['learn','LEARN'],['flow','FLOW'],['body','BODY'],['progress','PROGRESS']].map(([p,n])=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${n}</button>`).join('')}</nav>`;
const shell=(content)=>`<main class="app"><header class="top"><div class="brand"><span>FLUID</span> → <span>WHIP</span> → <span>WEAPON</span></div><div class="pill">FLUID I · RESTORE</div></header>${content}${nav()}</main>`;
function go(p){state.page=p;save();render()}
function home(){let pct=Math.min(100,18+state.completed*3);return `<section class="hero"><div class="eyebrow">TODAY · BUILD THE BASE</div><h1>Connect<br>the chain.</h1><p>Your current mission is to rebuild mobility, trunk control, balance and continuous movement before adding speed.</p><button class="primary" onclick="go('train')">BEGIN TRAINING</button></section><div class="grid"><section class="card"><div class="eyebrow">CURRENT STAGE</div><h3>FLUID I — Restore</h3><div class="progress"><i style="width:${pct}%"></i></div><div class="muted">${pct}% foundation development</div></section><section class="card"><div class="eyebrow">TRAINING RECORD</div><div class="metrics"><div class="metric"><b>${state.sessions}</b><small>sessions</small></div><div class="metric"><b>${state.completed}</b><small>moves</small></div><div class="metric"><b>${DB.moves.length}</b><small>today</small></div></div></section><section class="card wide"><div class="eyebrow">TODAY'S CHAIN</div><h3>Movement architecture</h3><div class="chain">${['ROOT','SHIFT','COIL','CHAIN','EXPRESS','RECOVER','FLOW'].map((x,i)=>`<span class="node">${x}</span>${i<6?'<span class="arrow">→</span>':''}`).join('')}</div></section><section class="card wide"><div class="eyebrow">RANGE CONTINUUM</div><h3>No dead range</h3><div class="range">${DB.ranges.map((r,i)=>`<span class="${i>2?'locked':''}">${r}</span>`).join('')}</div></section></div>`}
function train(){return `<h1 class="section-title">Today's Training</h1><section class="card wide"><div class="eyebrow">FLUID 01 · FOUNDATION</div><h3>Build the Base</h3><p class="muted">ROOT → SHIFT → CONNECT → FLOW</p><div class="workout">${DB.moves.map((m,i)=>`<div class="move"><div class="move-icon">${i+1}</div><div><small>${m.phase}</small><strong>${m.name}</strong><small>${m.chain}</small></div><span class="tag">${m.dose}</span></div>`).join('')}</div><br><div class="actions"><button class="primary" onclick="completeSession()">COMPLETE SESSION</button><button class="secondary" onclick="go('flow')">FLOW MODE</button></div><p class="notice">Training rule: new or sharp pain is not a progression signal. Stop the provoking movement and reassess before continuing.</p></section>`}
function learn(){return `<h1>Learn</h1><div class="grid">${DB.stages.map(s=>`<section class="card ${s.locked?'locked':''}"><div class="eyebrow">${s.locked?'LOCKED':'ACTIVE'}</div><h3>${s.name}</h3><p class="muted">${s.verb}</p></section>`).join('')}<section class="card wide"><div class="eyebrow">SYSTEM LANGUAGE</div><h3>One movement engine</h3><div class="chain">${['BREATHE','ROOT','BRACE','SHIFT','STEP','TURN','COIL','FRAME','REDIRECT','EXPRESS','RECOVER'].map(x=>`<span class="node">${x}</span>`).join('')}</div></section></div>`}
const prompts=['ROOT','SHIFT','STEP','TURN','COIL','RECOVER','FLOW'];
function flow(){let word=prompts[state.flowIndex%prompts.length];return `<h1>Flow Lab</h1><section class="card wide flow-prompt"><div class="eyebrow">SOLO MOVEMENT PROMPT</div><div class="flow-word">${word}</div><p class="muted">Move slowly. Preserve your base. Do not force range of motion.</p><div class="actions" style="justify-content:center"><button class="primary" onclick="nextFlow()">NEXT PROMPT</button><button class="secondary" onclick="state.flowIndex=0;save();render()">RESET</button></div></section>`}
function body(){return `<h1>Body</h1><section class="card wide"><div class="eyebrow">PHYSICAL CHASSIS</div><h3>Current foundation</h3>${DB.competencies.map(c=>`<div style="margin:16px 0"><div style="display:flex;justify-content:space-between"><b>${c[1]}</b><span class="muted">${Math.min(100,c[2]+state.sessions*2)}%</span></div><div class="progress"><i style="width:${Math.min(100,c[2]+state.sessions*2)}%"></i></div></div>`).join('')}</section>`}
function progress(){return `<h1>Progress</h1><div class="grid"><section class="card"><div class="eyebrow">MOVEMENT PASSPORT</div><h3>FLUID I</h3><p>Root I ${state.sessions>=1?'✓':'○'}<br>Core 360 I ${state.sessions>=2?'✓':'○'}<br>Weight Shift I ${state.sessions>=3?'✓':'○'}<br>Flow I ${state.sessions>=5?'✓':'○'}</p></section><section class="card"><div class="eyebrow">NEXT GATE</div><h3>FLUID II — Connect</h3><p class="muted">Unlocks after foundation competencies are demonstrated. Time alone does not advance the stage.</p></section></div>`}
function completeSession(){state.sessions++;state.completed+=DB.moves.length;save();go('progress')}
function nextFlow(){state.flowIndex=(state.flowIndex+1)%prompts.length;save();render()}
function render(){let views={home,train,learn,flow,body,progress};document.getElementById('app').innerHTML=shell(views[state.page]())}
render();