const baseMoves=[
{id:'breath',name:'360° Breathing + Brace',phase:'ARRIVE',why:'Build pressure control and trunk awareness.',chain:'BREATHE → BRACE',dose:['4 breaths','5 breaths','6 breaths'],reg:'Supine relaxed breathing',prog:'Standing 360° brace'},
{id:'root',name:'Supported Root Stance',phase:'ROOT',why:'Organize the feet, hips and trunk without excess tension.',chain:'ROOT → ALIGN',dose:['2 × 15 sec','3 × 20 sec','3 × 30 sec'],reg:'Two-hand support',prog:'Light fingertip support'},
{id:'shift',name:'Supported Weight Shift',phase:'FLUID',why:'Transfer mass while preserving balance.',chain:'ROOT → SHIFT → RECOVER',dose:['4 / side','6 / side','8 / side'],reg:'Small-range shift',prog:'Shift + controlled step'},
{id:'bird',name:'Bird Dog',phase:'STRUCTURE',why:'Develop anti-rotation for chained movement.',chain:'BRACE → REACH → RESIST',dose:['3 / side','5 / side','7 / side'],reg:'Single-limb reach',prog:'Longer controlled hold'},
{id:'sit',name:'Supported Sit-to-Stand',phase:'BUILD',why:'Rebuild the squat family from accessible range.',chain:'ROOT → HINGE → DRIVE',dose:['3 reps','5 reps','8 reps'],reg:'Higher seat + hand support',prog:'Lower seat / less support'},
{id:'flow',name:'Step–Shift–Turn Flow',phase:'FLOW',why:'Link locomotion into continuous controlled movement.',chain:'STEP → SHIFT → TURN → RECOVER',dose:['2 × 30 sec','3 × 45 sec','3 × 60 sec'],reg:'Shift + turn without step',prog:'Continuous multidirectional flow'},
{id:'walk',name:'Easy Walk',phase:'CONDITION',why:'Build gait quality and aerobic capacity.',chain:'ROOT → LOCOMOTE → BREATHE',dose:['6 min','10 min','15 min'],reg:'Short easy walk',prog:'Longer brisk intervals'},
{id:'return',name:'Return Sequence',phase:'RETURN',why:'Downshift and restore easy motion.',chain:'BREATHE → RELEASE → RESET',dose:['2 min','3 min','4 min'],reg:'Seated breathing',prog:'Standing mobility flow'}];
const allMoves=[...baseMoves,...Object.values(FLUID.extraMoves)];
const byId=id=>allMoves.find(m=>m.id===id);
const defaults={page:'home',sessions:0,totalMoves:0,flowIndex:0,readiness:null,scale:0,activeMove:0,done:[],quick:null,fluidLevel:'F1',sessionId:'F1-A',earned:[],favorites:[],learned:[]};
let state={...defaults,...JSON.parse(localStorage.getItem('fww-state-v4')||'{}')};
const save=()=>localStorage.setItem('fww-state-v4',JSON.stringify(state));
const currentLevel=()=>FLUID.levels.find(l=>l.id===state.fluidLevel)||FLUID.levels[0];
const currentSession=()=>FLUID.sessions.find(s=>s.id===state.sessionId)||FLUID.sessions[0];
const sessionMoves=()=>currentSession().moves.map(byId).filter(Boolean);
function go(page){state.page=page;save();render()}
const navItems=[['home','⌂','DASHBOARD'],['train','◫','TRAIN'],['body','◉','BODY'],['flow','⌁','FLOW'],['progress','▥','PROGRESS'],['learn','▤','MANUAL']];
const nav=()=>`<nav class="nav">${navItems.map(([p,icon,n])=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')"><b>${icon}</b><span>${n}</span></button>`).join('')}</nav>`;
const shell=c=>`<main class="app"><header class="top"><button class="logo" onclick="go('home')"><b>FWW</b><small>FLUID | WHIP | WEAPON</small></button><div class="desktop-nav">${navItems.map(([p,icon,n])=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')"><b>${icon}</b><span>${n}</span></button>`).join('')}</div><div class="profile-chip"><span class="avatar-mini">V</span><span>VANGUARD<br><small>${currentLevel().id} · ${currentLevel().name}</small></span></div></header>${c}${nav()}</main>`;
function home(){let level=currentLevel(),s=currentSession(),pct=Math.round(level.gate.filter(x=>state.earned.includes(x)).length/level.gate.length*100);return `<section class="hero"><div class="hero-copy"><div class="eyebrow">TODAY'S FOCUS · ${level.id} ${level.name}</div><h1>${s.name}</h1><p>${level.mission}</p><div class="actions"><button class="primary" onclick="startReadiness()">▶ START TRAINING</button><button class="secondary" onclick="go('curriculum')">CHOOSE SESSION</button></div></div><div class="hero-mark"><span>F</span><b>${pct}%</b><small>COMPETENCY</small></div></section><div class="grid"><section class="card"><div class="eyebrow">MOVEMENT PASSPORT</div><h3>${level.id} · ${level.name}</h3><div class="progress"><i style="width:${pct}%"></i></div><div class="passport-mini">${level.gate.slice(0,4).map(id=>`<span>${state.earned.includes(id)?'✓':'○'} ${FLUID.competencies[id].name}</span>`).join('')}</div></section><section class="card"><div class="eyebrow">TRAINING RECORD</div><div class="metrics"><div class="metric"><b>${state.sessions}</b><small>SESSIONS</small></div><div class="metric"><b>${state.totalMoves}</b><small>MOVES</small></div><div class="metric"><b>${state.earned.length}</b><small>COMPETENCIES</small></div></div></section><section class="card wide"><div class="eyebrow">SESSION CHAIN</div><h3>${s.focus}</h3><div class="chain">${s.chain.split(' → ').map((x,i,a)=>`<span class="node">${x}</span>${i<a.length-1?'<span class="arrow">→</span>':''}`).join('')}</div></section></div>`}
function curriculum(){return `<div class="pagehead"><div><div class="eyebrow">TRAINING SYSTEM</div><h1>FLUID Curriculum</h1></div><button class="secondary" onclick="quickTrain()">QUICK TRAIN</button></div>${FLUID.levels.map(level=>{let unlocked=level.id==='F1'||(level.id==='F2'&&FLUID.levels[0].gate.every(x=>state.earned.includes(x)))||(level.id==='F3'&&FLUID.levels[1].gate.every(x=>state.earned.includes(x)));return `<section class="card wide ${unlocked?'':'locked'}"><div class="eyebrow">${level.id} · ${level.name}</div><h3>${level.mission}</h3><div class="workout">${FLUID.sessions.filter(s=>s.level===level.id).map(s=>`<button class="move" ${unlocked?`onclick="chooseSession('${s.id}')"`:''}><div class="move-icon">${s.id.split('-')[1]}</div><div class="move-copy"><small>${s.focus}</small><strong>${s.name}</strong><small>${s.chain}</small></div><span class="tag">${unlocked?'OPEN':'LOCKED'}</span></button>`).join('')}</div></section>`}).join('')}`}
function chooseSession(id){let s=FLUID.sessions.find(x=>x.id===id);state.sessionId=id;state.fluidLevel=s.level;state.done=[];save();go('home')}
function startReadiness(){state.page='readiness';save();render()}
function readiness(){return `<div class="pagehead"><div><div class="eyebrow">PRE-SESSION</div><h1>Readiness Check</h1></div></div><section class="card wide"><div class="choice-grid"><button onclick="setReady('good')"><b>READY</b><small>No new pain; normal energy</small></button><button onclick="setReady('limited')"><b>LIMITED</b><small>Stiff, tired, or reduced capacity</small></button><button onclick="setReady('pain')"><b>NEW / SHARP PAIN</b><small>Do not train through it</small></button></div></section>`}
function setReady(r){state.readiness=r;state.scale=r==='limited'?0:1;state.done=[];state.activeMove=0;state.page=r==='pain'?'pain':'train';save();render()}
function pain(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">SESSION PAUSED</div><h1>Don't train through sharp pain.</h1><p>Skip the provoking activity. Seek medical evaluation for severe or persistent pain or concerning neurologic/systemic symptoms.</p><button class="secondary" onclick="go('home')">RETURN HOME</button></div></section>`}
function train(){let moves=sessionMoves(),s=currentSession(),scale=['FOUNDATION','BUILD','PERFORMANCE'][state.scale];return `<div class="pagehead"><div><div class="eyebrow">${s.id} · ${currentLevel().name}</div><h1>${s.name}</h1><p>${s.chain}</p></div><div class="session-count">${state.done.length}/${moves.length}<small>COMPLETE</small></div></div><section class="card wide"><div class="level-tabs">${['FOUNDATION','BUILD','PERFORMANCE'].map((x,i)=>`<button class="${state.scale===i?'selected':''}" onclick="state.scale=${i};save();render()">${x}</button>`).join('')}</div><div class="workout">${moves.map((m,i)=>`<button class="move ${state.done.includes(m.id)?'move-done':''}" onclick="openMove(${i})"><div class="move-icon">${state.done.includes(m.id)?'✓':i+1}</div><div class="move-copy"><small>${m.phase}</small><strong>${m.name}</strong><small>${m.chain}</small></div><span class="tag">${m.dose[state.scale]}</span></button>`).join('')}</div><br><button class="primary full" onclick="finishSession()" ${state.done.length<moves.length?'disabled':''}>COMPLETE SESSION</button></section>`}
function openMove(i){state.activeMove=i;state.page='move';save();render()}
function movementCode(m){return `${currentLevel().id}.${state.activeMove+1}.${state.scale+1}`}
function moveView(){let m=sessionMoves()[state.activeMove],done=state.done.includes(m.id),fav=state.favorites.includes(m.id),learned=state.learned.includes(m.id),code=movementCode(m);return `<div class="crumb">FLUID I › ${currentLevel().id} ${currentLevel().name} › ${currentSession().name.toUpperCase()} › ${m.name.toUpperCase()}</div><section class="movement-layout"><article class="movement-main"><div class="movement-title"><div><h1>${m.name}</h1><h4>${m.phase} · ${['FOUNDATION','BUILD','PERFORMANCE'][state.scale]}</h4></div></div><div class="visual-stage"><div class="avatar-figure"><div class="head"></div><div class="torso"></div><div class="arm a1"></div><div class="arm a2"></div><div class="leg l1"></div><div class="leg l2"></div></div><div class="visual-note"><b>LOCKED AVATAR VISUAL</b><span>Anatomically reviewed movement artwork replaces this schematic asset-by-asset.</span></div></div><div class="cue-grid"><div><b>KEY POINTS</b><span>✓ Preserve tall, organized posture</span><span>✓ Brace without holding your breath</span><span>✓ Move only through controlled range</span><span>✓ Return to a stable base</span></div><div><b>MOVEMENT CHAIN</b>${m.chain.split(' → ').map(x=>`<span>→ ${x}</span>`).join('')}</div></div></article><aside class="movement-side"><section class="sidecard"><div class="eyebrow">VIEWS</div><div class="view-grid"><button>FRONT</button><button class="selected">SIDE</button><button>BACK</button></div></section><section class="sidecard"><div class="eyebrow">PROGRESSION</div><b>${m.prog}</b><small>Earn through clean control.</small></section><section class="sidecard"><div class="eyebrow">MOVEMENT PASSPORT</div><h3>${code}</h3><p>${learned?'✓ Learned':'○ Learned'}<br>${done?'✓ Practiced':'○ Practiced'}<br>○ Mastered</p></section></aside></section><section class="statsbar"><div><b>${m.dose[state.scale]}</b><small>VOLUME</small></div><div><b>${state.scale===0?'SLOW':state.scale===1?'CONTROLLED':'QUICK'}</b><small>TEMPO</small></div><div><b>AS NEEDED</b><small>REST</small></div><div><b>${m.phase}</b><small>PATTERN</small></div></section><section class="card wide"><div class="eyebrow">DESCRIPTION</div><p>${m.why}</p><div class="level-options">${['FOUNDATION','BUILD','PERFORMANCE'].map((x,i)=>`<button class="${state.scale===i?'selected':''}" onclick="state.scale=${i};save();render()"><b>${x}</b><span>${m.dose[i]}</span></button>`).join('')}</div><div class="actions move-actions"><button class="secondary" onclick="toggleFavorite('${m.id}')">${fav?'★ FAVORITED':'☆ ADD TO FAVORITES'}</button><button class="primary" onclick="markMove('${m.id}')">${done?'✓ PRACTICED':'▶ START / COMPLETE EXERCISE'}</button><button class="secondary" onclick="go('flow')">VIEW IN FLOW</button></div></section>`}
function toggleFavorite(id){let i=state.favorites.indexOf(id);i>=0?state.favorites.splice(i,1):state.favorites.push(id);save();render()}
function markMove(id){if(!state.done.includes(id))state.done.push(id);if(!state.learned.includes(id))state.learned.push(id);save();render()}
function finishSession(){let moves=sessionMoves();if(state.done.length<moves.length)return;state.sessions++;state.totalMoves+=state.done.length;awardFromSession();state.done=[];state.readiness=null;state.page='progress';save();render()}
function awardFromSession(){let map={'F1-A':['breath360','rootBase','weightShift','coreAntiRotation'],'F1-B':['hingeAccess','coreAntiRotation'],'F1-C':['gaitBase','weightShift'],'F2-A':['contralateral','stepShift','singleLeg'],'F2-B':['hipShoulder','rotationControl'],'F3-A':['stepTurn','spiralFlow','directionChange','continuousFlow','flowEndurance']};(map[state.sessionId]||[]).forEach(x=>{if(!state.earned.includes(x))state.earned.push(x)})}
function quickTrain(){state.quick={minutes:10};state.page='quick';save();render()}
function quick(){let generated=state.quick?.generated||[];return `<div class="pagehead"><div><div class="eyebrow">TRAIN</div><h1>Quick Train</h1></div></div><section class="card wide"><div class="level-tabs">${[10,20,30,45].map(n=>`<button class="${state.quick.minutes===n?'selected':''}" onclick="state.quick.minutes=${n};save();render()">${n} MIN</button>`).join('')}</div><button class="primary" onclick="generateQuick()">GENERATE SESSION</button></section>${generated.length?`<section class="card wide">${generated.map(m=>`<div class="move"><div class="move-icon">•</div><div class="move-copy"><small>${m.phase}</small><strong>${m.name}</strong></div><span class="tag">${m.dose[0]}</span></div>`).join('')}</section>`:''}`}
function generateQuick(){let count=state.quick.minutes<=10?3:state.quick.minutes<=20?5:7;state.quick.generated=sessionMoves().slice(0,count);save();render()}
function learn(){return `<div class="pagehead"><div><div class="eyebrow">REFERENCE</div><h1>Manual</h1></div></div><div class="grid">${[['FLUID','Connect the Chain',false],['WHIP','Accelerate the Chain',true],['WEAPON','Apply the Chain',true]].map(s=>`<section class="card ${s[2]?'locked':''}"><div class="eyebrow">${s[2]?'COMING LATER':'ACTIVE'}</div><h3>${s[0]}</h3><p>${s[1]}</p></section>`).join('')}</div>`}
const prompts=['ROOT','SHIFT','STEP','TURN','COIL','RECOVER','FLOW'];
function flow(){let word=prompts[state.flowIndex%prompts.length];return `<div class="pagehead"><div><div class="eyebrow">GUIDED MOVEMENT</div><h1>Flow Mode</h1></div></div><section class="card wide flow-prompt"><div class="flow-orbit"></div><div class="flow-word">${word}</div><p>Let the movement find you. Preserve the base; never force range.</p><div class="actions center"><button class="primary" onclick="state.flowIndex=(state.flowIndex+1)%prompts.length;save();render()">NEXT</button><button class="secondary" onclick="speakFlow()">VOICE ON</button></div></section>`}
function speakFlow(){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(prompts[state.flowIndex%prompts.length]))}}
function body(){let domains={};Object.entries(FLUID.competencies).forEach(([id,c])=>{domains[c.domain]??={n:0,e:0};domains[c.domain].n++;if(state.earned.includes(id))domains[c.domain].e++});return `<div class="pagehead"><div><div class="eyebrow">YOUR PROFILE</div><h1>Body</h1></div></div><div class="body-dashboard"><div class="body-silhouette"><div class="avatar-figure large"><div class="head"></div><div class="torso"></div><div class="arm a1"></div><div class="arm a2"></div><div class="leg l1"></div><div class="leg l2"></div></div></div><section class="card wide"><div class="eyebrow">PHYSICAL CHASSIS</div>${Object.entries(domains).map(([d,v])=>{let p=Math.round(v.e/v.n*100);return `<div class="body-row"><div><b>${d}</b><span>${p}%</span></div><div class="progress"><i style="width:${p}%"></i></div></div>`}).join('')}</section></div>`}
function progress(){return `<div class="pagehead"><div><div class="eyebrow">MOVEMENT PASSPORT</div><h1>Progress</h1></div></div>${FLUID.levels.map(level=>{let got=level.gate.filter(x=>state.earned.includes(x)).length;return `<section class="card wide"><div class="eyebrow">${level.id} · ${level.name}</div><h3>${got}/${level.gate.length} competencies</h3><div class="progress"><i style="width:${Math.round(got/level.gate.length*100)}%"></i></div><div class="passport">${level.gate.map(id=>`<span class="${state.earned.includes(id)?'earned':''}">${state.earned.includes(id)?'✓':'○'} ${FLUID.competencies[id].name}</span>`).join('')}</div></section>`}).join('')}`}
function render(){let views={home,curriculum,readiness,pain,train,move:moveView,quick,learn,flow,body,progress};document.getElementById('app').innerHTML=shell((views[state.page]||home)())}
render();