const DB={
 competencies:[['mobility','Mobility',38],['core','Core',24],['balance','Balance',31],['strength','Strength',22],['flow','Flow',18],['conditioning','Conditioning',28]],
 moves:[
 {id:'breath',name:'360° Breathing + Brace',phase:'ARRIVE',why:'Build pressure control and trunk awareness.',chain:'BREATHE → BRACE',dose:['4 breaths','5 breaths','6 breaths'],reg:'Supine relaxed breathing',prog:'Standing 360° brace'},
 {id:'root',name:'Supported Root Stance',phase:'ROOT',why:'Organize the feet, hips and trunk without excess tension.',chain:'ROOT → ALIGN',dose:['2 × 15 sec','3 × 20 sec','3 × 30 sec'],reg:'Two-hand support',prog:'Light fingertip support'},
 {id:'shift',name:'Supported Weight Shift',phase:'FLUID',why:'Transfer mass while preserving balance.',chain:'ROOT → SHIFT → RECOVER',dose:['4 / side','6 / side','8 / side'],reg:'Small-range shift',prog:'Shift + controlled step'},
 {id:'bird',name:'Bird Dog',phase:'STRUCTURE',why:'Develop anti-rotation for chained movement.',chain:'BRACE → REACH → RESIST',dose:['3 / side','5 / side','7 / side'],reg:'Single-limb reach',prog:'Longer controlled hold'},
 {id:'sit',name:'Supported Sit-to-Stand',phase:'BUILD',why:'Rebuild the squat family from accessible range.',chain:'ROOT → HINGE → DRIVE',dose:['3 reps','5 reps','8 reps'],reg:'Higher seat + hand support',prog:'Lower seat / less support'},
 {id:'flow',name:'Step–Shift–Turn Flow',phase:'FLOW',why:'Link locomotion into continuous controlled movement.',chain:'STEP → SHIFT → TURN → RECOVER',dose:['2 × 30 sec','3 × 45 sec','3 × 60 sec'],reg:'Shift + turn without step',prog:'Continuous multidirectional flow'},
 {id:'walk',name:'Easy Walk',phase:'CONDITION',why:'Build gait quality and aerobic capacity.',chain:'ROOT → LOCOMOTE → BREATHE',dose:['6 min','10 min','15 min'],reg:'Short easy walk',prog:'Longer brisk intervals'},
 {id:'return',name:'Return Sequence',phase:'RETURN',why:'Downshift and restore easy motion.',chain:'BREATHE → RELEASE → RESET',dose:['2 min','3 min','4 min'],reg:'Seated breathing',prog:'Standing mobility flow'}
 ],ranges:['OUTSIDE','LOW LINE','LONG','MID','POCKET','CONTACT','REDIRECT','CLINCH','GROUND']};
const defaults={page:'home',sessions:0,totalMoves:0,flowIndex:0,readiness:null,level:0,activeMove:0,done:[],quick:null};
let state={...defaults,...JSON.parse(localStorage.getItem('fww-state-v2')||'{}')};
const save=()=>localStorage.setItem('fww-state-v2',JSON.stringify(state));
const esc=s=>String(s).replaceAll("'","\\'");
function go(page){state.page=page;save();render()}
const nav=()=>`<nav class="nav">${[['home','HOME'],['train','TRAIN'],['learn','LEARN'],['flow','FLOW'],['body','BODY'],['progress','PROGRESS']].map(([p,n])=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${n}</button>`).join('')}</nav>`;
const shell=c=>`<main class="app"><header class="top"><div class="brand"><span>FLUID</span> → <span>WHIP</span> → <span>WEAPON</span></div><div class="pill">FLUID I · RESTORE</div></header>${c}${nav()}</main>`;
function home(){let pct=Math.min(100,18+state.sessions*6);return `<section class="hero"><div class="eyebrow">TODAY · BUILD THE BASE</div><h1>Connect<br>the chain.</h1><p>One adaptive session. Clear movement cards. The complexity stays underneath.</p><div class="actions"><button class="primary" onclick="startReadiness()">BEGIN TRAINING</button><button class="secondary" onclick="quickTrain()">QUICK TRAIN</button></div></section><div class="grid"><section class="card"><div class="eyebrow">CURRENT STAGE</div><h3>FLUID I — Restore</h3><div class="progress"><i style="width:${pct}%"></i></div><div class="muted">${pct}% foundation development</div></section><section class="card"><div class="eyebrow">TRAINING RECORD</div><div class="metrics"><div class="metric"><b>${state.sessions}</b><small>sessions</small></div><div class="metric"><b>${state.totalMoves}</b><small>moves</small></div><div class="metric"><b>${state.done.length}</b><small>today</small></div></div></section><section class="card wide"><div class="eyebrow">TODAY'S CHAIN</div><div class="chain">${['ROOT','SHIFT','COIL','CHAIN','EXPRESS','RECOVER','FLOW'].map((x,i)=>`<span class="node">${x}</span>${i<6?'<span class="arrow">→</span>':''}`).join('')}</div></section><section class="card wide"><div class="eyebrow">NO-DEAD-RANGE MAP</div><div class="range">${DB.ranges.map((r,i)=>`<span class="${i>2?'locked':''}">${r}</span>`).join('')}</div></section></div>`}
function startReadiness(){state.page='readiness';save();render()}
function readiness(){return `<h1>Readiness Check</h1><section class="card wide"><div class="eyebrow">BEFORE YOU MOVE</div><h3>How does your body feel right now?</h3><div class="choice-grid"><button onclick="setReady('good')"><b>READY</b><small>No new pain; normal energy</small></button><button onclick="setReady('limited')"><b>LIMITED</b><small>Stiff, tired, or reduced capacity</small></button><button onclick="setReady('pain')"><b>NEW / SHARP PAIN</b><small>Do not train through it</small></button></div><p class="notice">This check changes the session. Sharp or new pain routes away from training rather than rewarding you for overriding it.</p></section>`}
function setReady(r){state.readiness=r;state.level=r==='limited'?0:1;state.done=[];state.activeMove=0;state.page=r==='pain'?'pain':'train';save();render()}
function pain(){return `<section class="hero"><div class="eyebrow">SESSION PAUSED</div><h1>Don't train through sharp pain.</h1><p>Skip the provoking activity today. If pain is severe, persists, follows a significant injury, or comes with weakness/numbness, bowel or bladder changes, fever, chest pain, or other concerning symptoms, seek appropriate medical evaluation.</p><button class="secondary" onclick="go('home')">RETURN HOME</button></section>`}
function train(){let scale=['FOUNDATION','BUILD','PERFORMANCE'][state.level];return `<h1>Today's Training</h1><section class="card wide"><div class="eyebrow">FLUID 01 · ${scale}</div><h3>Build the Base</h3><div class="level-tabs">${['FOUNDATION','BUILD','PERFORMANCE'].map((x,i)=>`<button class="${state.level===i?'selected':''}" onclick="setLevel(${i})">${x}</button>`).join('')}</div><div class="workout">${DB.moves.map((m,i)=>`<button class="move ${state.done.includes(m.id)?'move-done':''}" onclick="openMove(${i})"><div class="move-icon">${state.done.includes(m.id)?'✓':i+1}</div><div class="move-copy"><small>${m.phase}</small><strong>${m.name}</strong><small>${m.chain}</small></div><span class="tag">${m.dose[state.level]}</span></button>`).join('')}</div><br><div class="actions"><button class="primary" onclick="finishSession()" ${state.done.length<DB.moves.length?'disabled':''}>COMPLETE SESSION</button><button class="secondary" onclick="go('flow')">FLOW MODE</button></div></section>`}
function setLevel(i){state.level=i;save();render()}
function openMove(i){state.activeMove=i;state.page='move';save();render()}
function moveView(){let m=DB.moves[state.activeMove];let done=state.done.includes(m.id);return `<button class="back" onclick="go('train')">← TODAY</button><section class="movement-hero"><div class="figure"><div class="figure-core">${state.activeMove+1}</div><span>CANONICAL VISUAL SLOT</span></div><div><div class="eyebrow">${m.phase}</div><h1>${m.name}</h1><div class="dose">${m.dose[state.level]}</div><div class="chain">${m.chain.split(' → ').map((x,i,a)=>`<span class="node">${x}</span>${i<a.length-1?'<span class="arrow">→</span>':''}`).join('')}</div><p>${m.why}</p></div></section><div class="grid"><section class="card"><div class="eyebrow">REGRESSION</div><h3>${m.reg}</h3><p class="muted">Use this when the standard version exceeds today's clean capacity.</p></section><section class="card"><div class="eyebrow">PROGRESSION</div><h3>${m.prog}</h3><p class="muted">Earn this through control—not by forcing range or speed.</p></section><section class="card wide"><div class="actions"><button class="primary" onclick="markMove('${esc(m.id)}')">${done?'COMPLETED ✓':'MARK COMPLETE'}</button><button class="secondary" onclick="nextMove()">NEXT MOVEMENT</button></div></section></div>`}
function markMove(id){if(!state.done.includes(id))state.done.push(id);save();render()}
function nextMove(){let m=DB.moves[state.activeMove];if(!state.done.includes(m.id))state.done.push(m.id);state.activeMove=Math.min(DB.moves.length-1,state.activeMove+1);save();render()}
function finishSession(){if(state.done.length<DB.moves.length)return;state.sessions++;state.totalMoves+=state.done.length;state.done=[];state.readiness=null;state.page='progress';save();render()}
function quickTrain(){state.quick={minutes:10,focus:'FULL SYSTEM'};state.page='quick';save();render()}
function quick(){return `<h1>Quick Train</h1><section class="card wide"><div class="eyebrow">GENERATE A SESSION</div><h3>How much time?</h3><div class="level-tabs">${[10,20,30,45].map(n=>`<button class="${state.quick.minutes===n?'selected':''}" onclick="state.quick.minutes=${n};save();render()">${n} MIN</button>`).join('')}</div><h3>Focus</h3><div class="level-tabs">${['FULL SYSTEM','MOBILITY','CORE','FLOW','RECOVERY'].map(x=>`<button class="${state.quick.focus===x?'selected':''}" onclick="state.quick.focus='${x}';save();render()">${x}</button>`).join('')}</div><br><button class="primary" onclick="generateQuick()">GENERATE</button></section>`}
function generateQuick(){let count=state.quick.minutes<=10?3:state.quick.minutes<=20?5:8;state.quick.generated=DB.moves.slice(0,count);render()}
function quickResult(){return state.quick?.generated?`<section class="card wide"><div class="eyebrow">${state.quick.minutes} MIN · ${state.quick.focus}</div><h3>Generated from current FLUID capacity</h3>${state.quick.generated.map(m=>`<div class="move"><div class="move-icon">•</div><div class="move-copy"><small>${m.phase}</small><strong>${m.name}</strong></div><span class="tag">${m.dose[0]}</span></div>`).join('')}</section>`:''}
function learn(){return `<h1>Learn</h1><div class="grid">${[['FLUID','Connect the Chain',false],['WHIP','Accelerate the Chain',true],['WEAPON','Apply the Chain',true]].map(s=>`<section class="card ${s[2]?'locked':''}"><div class="eyebrow">${s[2]?'LOCKED':'ACTIVE'}</div><h3>${s[0]}</h3><p class="muted">${s[1]}</p></section>`).join('')}<section class="card wide"><div class="eyebrow">SYSTEM LANGUAGE</div><div class="chain">${['BREATHE','ROOT','BRACE','SHIFT','STEP','TURN','COIL','FRAME','REDIRECT','EXPRESS','RECOVER'].map(x=>`<span class="node">${x}</span>`).join('')}</div></section></div>`}
const prompts=['ROOT','SHIFT','STEP','TURN','COIL','RECOVER','FLOW'];
function flow(){let word=prompts[state.flowIndex%prompts.length];return `<h1>Flow Lab</h1><section class="card wide flow-prompt"><div class="eyebrow">SOLO MOVEMENT PROMPT</div><div class="flow-word">${word}</div><p class="muted">Move slowly. Preserve your base. No forced range.</p><div class="actions" style="justify-content:center"><button class="primary" onclick="nextFlow()">NEXT PROMPT</button><button class="secondary" onclick="speakFlow()">VOICE PROMPT</button></div></section>`}
function nextFlow(){state.flowIndex=(state.flowIndex+1)%prompts.length;save();render()}
function speakFlow(){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(prompts[state.flowIndex%prompts.length]))}}
function body(){return `<h1>Body</h1><section class="card wide"><div class="eyebrow">PHYSICAL CHASSIS</div><h3>Current foundation</h3>${DB.competencies.map(c=>{let v=Math.min(100,c[2]+state.sessions*2);return `<div class="body-row"><div><b>${c[1]}</b><span>${v}%</span></div><div class="progress"><i style="width:${v}%"></i></div></div>`}).join('')}</section>`}
function progress(){return `<h1>Progress</h1><div class="grid"><section class="card"><div class="eyebrow">MOVEMENT PASSPORT</div><h3>FLUID I</h3><p>Root I ${state.sessions>=1?'✓':'○'}<br>Core 360 I ${state.sessions>=2?'✓':'○'}<br>Weight Shift I ${state.sessions>=3?'✓':'○'}<br>Flow I ${state.sessions>=5?'✓':'○'}</p></section><section class="card"><div class="eyebrow">NEXT GATE</div><h3>FLUID II — Connect</h3><p class="muted">Competency unlocks progression. The calendar does not.</p></section></div>`}
function render(){let views={home,readiness,pain,train,move:moveView,quick:()=>quick()+quickResult(),learn,flow,body,progress};document.getElementById('app').innerHTML=shell((views[state.page]||home)())}
render();