(()=>{
 function h(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function currentWeek(){const n=Number(localStorage.getItem('fww-program-week-v11')||1);return Math.min(24,Math.max(1,n))}
 function setWeek(n){const week=Math.min(24,Math.max(1,n));localStorage.setItem('fww-program-week-v11',String(week));if(window.FWW_PASSPORT){const s=FWW_PASSPORT.load();s.week=week;s.phase=FWW_COMPREHENSIVE.phaseForWeek(week).id;FWW_PASSPORT.save(s)}renderComprehensiveProgram()}
 function doneKey(id){return `fww-session-done-v11:${currentWeek()}:${id}`}
 window.completeComprehensiveSession=function(id){if(localStorage.getItem(doneKey(id))==='1'){renderComprehensiveProgram();return}const s=FWW_WORKOUTS.sessions[id];if(!s)return;localStorage.setItem(doneKey(id),'1');if(window.FWW_PASSPORT)FWW_PASSPORT.completeSession({session:s.name,phase:FWW_COMPREHENSIVE.phaseForWeek(currentWeek()).id});renderComprehensiveProgram()};
 window.openComprehensiveSession=function(id){const s=FWW_WORKOUTS.sessions[id];if(!s)return;const done=localStorage.getItem(doneKey(id))==='1';document.getElementById('app').innerHTML=`<div class="app"><div class="pagehead"><div><div class="eyebrow">COMPREHENSIVE TRAINING · WEEK ${currentWeek()}</div><h1>${h(s.name)}</h1><p>${h(s.rounds)}</p></div></div><div class="workout">${s.items.map((x,i)=>`<article class="card wide"><div class="eyebrow">${String(i+1).padStart(2,'0')}</div><h3>${h(x.name)}</h3><p><b>${h(x.dose||'')}</b></p>${x.focus?`<p>${h(x.focus)}</p>`:''}${x.reg?`<p><small>REGRESSION</small><br>${h(x.reg)}</p>`:''}${x.prog?`<p><small>PROGRESSION</small><br>${h(x.prog)}</p>`:''}${x.rest?`<span class="tag">REST ${h(x.rest)}</span>`:''}</article>`).join('')}</div><div class="actions"><button class="secondary" onclick="renderComprehensiveProgram()">BACK TO PROGRAM</button><button class="primary" onclick="completeComprehensiveSession('${id}')" ${done?'disabled':''}>${done?'✓ SESSION COMPLETED':'COMPLETE SESSION'}</button></div></div>`;window.scrollTo(0,0)};
 window.renderComprehensiveProgram=function(){const week=currentWeek(),w=FWW_COMPREHENSIVE.buildWeek(week),p=FWW_COMPREHENSIVE.phases.find(x=>x.id===w.phase),ids=FWW_WORKOUTS.prescriptionForPhase(p.id),tests=FWW_WORKOUTS.tests[p.id]||[],completed=ids.filter(id=>localStorage.getItem(doneKey(id))==='1').length;document.getElementById('app').innerHTML=`<div class="app"><section class="hero command-hero"><div class="hero-copy"><div class="eyebrow">24-WEEK COMPLETE SYSTEM · WEEK ${week}</div><h1>${h(p.name)}</h1><p>${h(p.goal)}</p><div class="actions"><button class="secondary" onclick="setComprehensiveWeek(${week-1})" ${week===1?'disabled':''}>← WEEK ${Math.max(1,week-1)}</button><button class="primary" onclick="setComprehensiveWeek(${week+1})" ${week===24?'disabled':''}>WEEK ${Math.min(24,week+1)} →</button></div></div></section><div class="card wide"><div class="eyebrow">PHASE ${h(p.id)} · WEEKS ${h(p.weeks)} · ${completed}/${ids.length} CURRENT SESSIONS COMPLETE</div><h3>Training Sessions</h3><div class="program-blocks">${ids.map(id=>{const s=FWW_WORKOUTS.sessions[id],done=localStorage.getItem(doneKey(id))==='1';return `<article><small>${done?'✓ COMPLETED':h(p.name)}</small><b>${h(s.name)}</b><span>${h(s.rounds)}</span><button class="${done?'secondary':'primary'} full" onclick="openComprehensiveSession('${id}')">${done?'REVIEW SESSION':'OPEN SESSION'}</button></article>`}).join('')}</div></div><div class="card wide"><div class="eyebrow">WEEKLY RHYTHM</div><h3>Seven-Day Structure</h3><div class="week-strip">${w.days.map(d=>`<button><b>${h(d.day)}</b><small>${h(d.name)}</small></button>`).join('')}</div></div><div class="card wide"><div class="eyebrow">COMPETENCY GATE</div><h3>${h(p.gate)}</h3>${tests.map(t=>`<div class="dash-line"><b>${h(t[0])}</b><span>${h(t[1])}</span></div>`).join('')}<button class="secondary full" onclick="renderPassportV11()">OPEN MOVEMENT PASSPORT</button></div><div class="card wide"><div class="eyebrow">RANGE CONTINUITY</div><h3>No Dead Zones</h3><div class="range-map">${FWW_COMPREHENSIVE.ranges.map(r=>`<button><small>${h(r.id)}</small><b>${h(r.name)}</b><span>${h(r.jobs.join(' · '))}</span></button>`).join('')}</div><p>${h(FWW_COMPREHENSIVE.rules.grappling)}</p></div></div>`;window.scrollTo(0,0)};
 window.setComprehensiveWeek=setWeek;if(window.AppRouter&&typeof AppRouter.register==='function')AppRouter.register('completeprogram',renderComprehensiveProgram);
})();