(()=>{
 function h(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function currentWeek(){const n=Number(localStorage.getItem('fww-program-week-v11')||1);return Math.min(24,Math.max(1,n))}
 function setWeek(n){const week=Math.min(24,Math.max(1,n));localStorage.setItem('fww-program-week-v11',String(week));if(window.FWW_PASSPORT){const s=FWW_PASSPORT.load();s.week=week;s.phase=FWW_COMPREHENSIVE.phaseForWeek(week).id;FWW_PASSPORT.save(s)}renderComprehensiveProgram()}
 function doneKey(id){return `fww-session-done-v11:${currentWeek()}:${id}`}
 function dayKey(i){return `fww-day-done-v11:${currentWeek()}:${i}`}
 function prescribedIds(){const p=FWW_COMPREHENSIVE.phaseForWeek(currentWeek());return FWW_WORKOUTS.prescriptionForPhase(p.id)}
 function sessionForDay(i){const w=FWW_COMPREHENSIVE.buildWeek(currentWeek()),d=w.days[i],ids=prescribedIds();if(!d)return null;const text=`${d.name} ${d.day}`.toLowerCase();if(/rest|recover|off|walk|mobility/.test(text))return ids.find(x=>/restoreflow/i.test(x))||null;if(/whip|speed/.test(text))return ids.find(x=>/whip/i.test(x))||ids[0];if(/weapon|range|adapt|defen|self/.test(text))return ids.find(x=>/range|adapt/i.test(x))||ids[0];if(/flow|skill|martial|tech/.test(text))return ids.find(x=>/flow/i.test(x))||ids.find(x=>!/restoreflow/i.test(x))||ids[0];if(/strength|chassis|fitness|body/.test(text))return ids.find(x=>/connect|restorea|restoreb/i.test(x))||ids[0];return ids[i%ids.length]||null}
 window.completeComprehensiveSession=function(id){if(localStorage.getItem(doneKey(id))==='1'){renderComprehensiveProgram();return}const s=FWW_WORKOUTS.sessions[id];if(!s)return;localStorage.setItem(doneKey(id),'1');if(window.FWW_PASSPORT)FWW_PASSPORT.completeSession({session:s.name,phase:FWW_COMPREHENSIVE.phaseForWeek(currentWeek()).id});renderComprehensiveProgram()};
 window.openComprehensiveDay=function(i){const w=FWW_COMPREHENSIVE.buildWeek(currentWeek()),d=w.days[i];if(!d)return;const sid=sessionForDay(i),s=sid?FWW_WORKOUTS.sessions[sid]:null,done=localStorage.getItem(dayKey(i))==='1';document.getElementById('app').innerHTML=`<div class="app"><div class="pagehead"><div><div class="eyebrow">WEEK ${currentWeek()} · ${h(d.day)}</div><h1>${h(d.name)}</h1><p>${s?'Today’s prescribed training session.':'Recovery / practice day.'}</p></div></div>${s?`<article class="card wide"><div class="eyebrow">TODAY'S PRESCRIPTION</div><h3>${h(s.name)}</h3><p>${h(s.rounds)}</p><button class="primary full" onclick="openComprehensiveSession('${sid}')">OPEN TRAINING</button></article>`:`<article class="card wide"><h3>Recovery Day</h3><p>Keep the chain easy: walking, comfortable mobility, relaxed breathing, and no forced intensity.</p></article>`}<div class="actions"><button class="secondary" onclick="renderComprehensiveProgram()">BACK TO WEEK</button><button class="primary" onclick="completeComprehensiveDay(${i})" ${done?'disabled':''}>${done?'✓ DAY COMPLETE':'COMPLETE DAY'}</button></div></div>`;window.scrollTo(0,0)};
 window.completeComprehensiveDay=function(i){if(localStorage.getItem(dayKey(i))==='1'){renderComprehensiveProgram();return}const w=FWW_COMPREHENSIVE.buildWeek(currentWeek()),d=w.days[i];if(!d)return;localStorage.setItem(dayKey(i),'1');const sid=sessionForDay(i);if(sid&&localStorage.getItem(doneKey(sid))!=='1')completeComprehensiveSession(sid);else{if(window.FWW_PASSPORT)FWW_PASSPORT.completeSession({session:`${d.day} — ${d.name}`,phase:FWW_COMPREHENSIVE.phaseForWeek(currentWeek()).id});renderComprehensiveProgram()}};
 window.openComprehensiveSession=function(id){const s=FWW_WORKOUTS.sessions[id];if(!s)return;const done=localStorage.getItem(doneKey(id))==='1';document.getElementById('app').innerHTML=`<div class="app"><div class="pagehead"><div><div class="eyebrow">COMPREHENSIVE TRAINING · WEEK ${currentWeek()}</div><h1>${h(s.name)}</h1><p>${h(s.rounds)}</p></div></div><div class="workout">${s.items.map((x,i)=>`<article class="card wide"><div class="eyebrow">${String(i+1).padStart(2,'0')}</div><h3>${h(x.name)}</h3><p><b>${h(x.dose||'')}</b></p>${x.focus?`<p>${h(x.focus)}</p>`:''}${x.reg?`<p><small>REGRESSION</small><br>${h(x.reg)}</p>`:''}${x.prog?`<p><small>PROGRESSION</small><br>${h(x.prog)}</p>`:''}${x.rest?`<span class="tag">REST ${h(x.rest)}</span>`:''}</article>`).join('')}</div><div class="actions"><button class="secondary" onclick="renderComprehensiveProgram()">BACK TO PROGRAM</button><button class="primary" onclick="completeComprehensiveSession('${id}')" ${done?'disabled':''}>${done?'✓ SESSION COMPLETED':'COMPLETE SESSION'}</button></div></div>`;window.scrollTo(0,0)};
 window.renderComprehensiveProgram=function(){const week=currentWeek(),w=FWW_COMPREHENSIVE.buildWeek(week),p=FWW_COMPREHENSIVE.phases.find(x=>x.id===w.phase),ids=FWW_WORKOUTS.prescriptionForPhase(p.id),tests=FWW_WORKOUTS.tests[p.id]||[],completed=ids.filter(id=>localStorage.getItem(doneKey(id))==='1').length,daysDone=w.days.filter((_,i)=>localStorage.getItem(dayKey(i))==='1').length;document.getElementById('app').innerHTML=`<div class="app"><section class="hero command-hero"><div class="hero-copy"><div class="eyebrow">24-WEEK COMPLETE SYSTEM · WEEK ${week}</div><h1>${h(p.name)}</h1><p>${h(p.goal)}</p><div class="actions"><button class="secondary" onclick="setComprehensiveWeek(${week-1})" ${week===1?'disabled':''}>← WEEK ${Math.max(1,week-1)}</button><button class="primary" onclick="setComprehensiveWeek(${week+1})" ${week===24?'disabled':''}>WEEK ${Math.min(24,week+1)} →</button></div></div></section><div class="card wide"><div class="eyebrow">PHASE ${h(p.id)} · WEEKS ${h(p.weeks)} · ${completed}/${ids.length} PRESCRIPTIONS COMPLETE</div><h3>Training Sessions</h3><div class="program-blocks">${ids.map(id=>{const s=FWW_WORKOUTS.sessions[id],done=localStorage.getItem(doneKey(id))==='1';return `<article><small>${done?'✓ COMPLETED':h(p.name)}</small><b>${h(s.name)}</b><span>${h(s.rounds)}</span><button class="${done?'secondary':'primary'} full" onclick="openComprehensiveSession('${id}')">${done?'REVIEW SESSION':'OPEN SESSION'}</button></article>`}).join('')}</div></div><div class="card wide"><div class="eyebrow">WEEKLY RHYTHM · ${daysDone}/7 DAYS COMPLETE</div><h3>Seven-Day Structure</h3><div class="week-strip">${w.days.map((d,i)=>{const done=localStorage.getItem(dayKey(i))==='1';return `<button onclick="openComprehensiveDay(${i})" class="${done?'done':''}"><b>${done?'✓ ':''}${h(d.day)}</b><small>${h(d.name)}</small></button>`}).join('')}</div></div><div class="card wide"><div class="eyebrow">COMPETENCY GATE</div><h3>${h(p.gate)}</h3>${tests.map(t=>`<div class="dash-line"><b>${h(t[0])}</b><span>${h(t[1])}</span></div>`).join('')}<button class="secondary full" onclick="renderPassportV11()">OPEN MOVEMENT PASSPORT</button></div><div class="card wide"><div class="eyebrow">RANGE CONTINUITY</div><h3>No Dead Zones</h3><div class="range-map">${FWW_COMPREHENSIVE.ranges.map(r=>`<button><small>${h(r.id)}</small><b>${h(r.name)}</b><span>${h(r.jobs.join(' · '))}</span></button>`).join('')}</div><p>${h(FWW_COMPREHENSIVE.rules.grappling)}</p></div></div>`;window.scrollTo(0,0)};
 window.setComprehensiveWeek=setWeek;if(window.AppRouter&&typeof AppRouter.register==='function')AppRouter.register('completeprogram',renderComprehensiveProgram);
})();