(()=>{
 state.fitSession=state.fitSession||'FIT-A';state.fitDone=state.fitDone||[];state.fitScale=Number.isInteger(state.fitScale)?state.fitScale:0;state.squatLevel=state.squatLevel||1;state.fitSessions=state.fitSessions||0;
 window.chooseFit=id=>{state.fitSession=id;state.fitDone=[];state.page='fitnessworkout';save();render()};
 window.completeFitMove=id=>{if(!state.fitDone.includes(id))state.fitDone.push(id);save();render()};
 window.finishFit=()=>{const s=CONDITIONING.sessions.find(x=>x.id===state.fitSession);if(state.fitDone.length<s.moves.length)return;state.fitSessions++;state.fitDone=[];state.page='fitness';save();render()};
 window.advanceSquat=()=>{if(state.squatLevel<CONDITIONING.squatLadder.length)state.squatLevel++;save();render()};
 window.fitnessHome=()=>{const sq=CONDITIONING.squatLadder[state.squatLevel-1];return `<div class="pagehead"><div><div class="eyebrow">PHYSICAL FOUNDATION · FITNESS MODE</div><h1>Chassis</h1><p>Mobility, core integrity, base strength and work capacity underneath FLUID → WHIP → WEAPON.</p></div><div class="session-count">${state.fitSessions}<small>FITNESS SESSIONS</small></div></div><section class="card wide"><div class="eyebrow">CURRENT SQUAT LADDER</div><h3>LEVEL ${state.squatLevel} · ${sq.name}</h3><p>${sq.test}</p><div class="progress"><i style="width:${state.squatLevel/CONDITIONING.squatLadder.length*100}%"></i></div><button class="secondary" onclick="advanceSquat()" ${state.squatLevel>=CONDITIONING.squatLadder.length?'disabled':''}>MARK TEST PASSED → NEXT LEVEL</button></section><section class="grid">${CONDITIONING.sessions.map(s=>`<article class="card"><div class="eyebrow">${s.id}</div><h3>${s.name}</h3><p>${s.focus}</p><small>${s.moves.length} movements</small><br><br><button class="primary" onclick="chooseFit('${s.id}')">START</button></article>`).join('')}</section><section class="card wide"><div class="eyebrow">TRAINING DOMAINS</div><div class="principle-grid">${CONDITIONING.domains.map((d,i)=>`<article><strong>0${i+1}</strong><div><b>${d.name}</b><span>${d.goal}</span></div></article>`).join('')}</div></section>`};
 window.fitnessWorkout=()=>{const s=CONDITIONING.sessions.find(x=>x.id===state.fitSession);return `<div class="pagehead"><div><div class="eyebrow">${s.id} · FITNESS MODE</div><h1>${s.name}</h1><p>${s.focus}</p></div><div class="session-count">${state.fitDone.length}/${s.moves.length}<small>COMPLETE</small></div></div><section class="card wide"><div class="level-options">${['FOUNDATION','BUILD','PERFORMANCE'].map((x,i)=>`<button class="${state.fitScale===i?'selected':''}" onclick="state.fitScale=${i};save();render()"><b>${x}</b></button>`).join('')}</div><div class="workout">${s.moves.map((id,i)=>{const m=conditioningExercise(id),done=state.fitDone.includes(id);return `<button class="move ${done?'move-done':''}" onclick="completeFitMove('${id}')"><div class="move-icon">${done?'✓':i+1}</div><div class="move-copy"><small>${m.domain.toUpperCase()} · ${m.equipment}</small><strong>${m.name}</strong><small>${m.chain}</small></div><span class="tag">${m.dose[state.fitScale]}</span></button>`}).join('')}</div><br><button class="primary full" onclick="finishFit()" ${state.fitDone.length<s.moves.length?'disabled':''}>COMPLETE SESSION</button></section><section class="card wide safety-card"><div class="eyebrow">PROGRESSION RULES</div>${CONDITIONING.rules.map(x=>`<p>• ${x}</p>`).join('')}</section>`};
 const oldRender=render;window.render=()=>{if(state.page==='fitness')document.getElementById('app').innerHTML=shell(fitnessHome());else if(state.page==='fitnessworkout')document.getElementById('app').innerHTML=shell(fitnessWorkout());else oldRender()};
 window.openFitness=()=>{state.page='fitness';save();render()};
 render();
})();