(()=>{
 const results=[];
 const check=(name,ok,detail='')=>results.push({name,ok:!!ok,detail});
 const requiredRoutes=['home','train','move','quick','flow','progress','learn','curriculum','body','pain','precheck','whipcurriculum','whiptrain','whipmove','weapon','weaponcurriculum','weapontrain','weaponmove','weaponlibrary','weapontech','adaptivelab','offenselibrary','combolab','fitness','fitnessworkout','readiness','program'];
 requiredRoutes.forEach(r=>check(`route:${r}`,AppRouter.has(r),AppRouter.has(r)?'registered':'missing'));
 ['earned','whipEarned','weaponEarned','fitDone'].forEach(k=>check(`state-array:${k}`,Array.isArray(state[k]),typeof state[k]));
 check('state:readiness-object',state.readiness&&typeof state.readiness==='object'&&!Array.isArray(state.readiness),typeof state.readiness);
 check('state:precheck-separated',state.precheckStatus===null||['good','limited','pain'].includes(state.precheckStatus),String(state.precheckStatus));
 const fluidIds=new Set(Object.keys(FLUID.competencies||{}));
 FLUID.levels.forEach(l=>(l.gate||[]).forEach(id=>check(`fluid-gate:${l.id}:${id}`,fluidIds.has(id),'competency exists')));
 const whipIds=new Set(Object.keys(WHIP.competencies||{}));
 WHIP.levels.forEach(l=>(l.gate||[]).forEach(id=>check(`whip-gate:${l.id}:${id}`,whipIds.has(id),'competency exists')));
 const sessionMoveIds=new Set([...allMoves.map(x=>x.id)]);
 FLUID.sessions.forEach(s=>s.moves.forEach(id=>check(`fluid-session:${s.id}:${id}`,sessionMoveIds.has(id),'movement exists')));
 WHIP.sessions.forEach(s=>s.moves.forEach(id=>check(`whip-session:${s.id}:${id}`,!!WHIP.drills[id],'drill exists')));
 check('unlock:whip-function',typeof whipUnlocked==='function');
 check('unlock:weapon-function',typeof weaponUnlocked==='function');
 check('state-controller',typeof AppState==='object');
 check('router-single-owner',window.render===AppRouter.render||typeof window.render==='function','router installed last');
 const failed=results.filter(x=>!x.ok);
 window.FWW_QA={results,failed,passed:results.length-failed.length,total:results.length,ok:failed.length===0,report(){return {ok:this.ok,passed:this.passed,total:this.total,failed:this.failed}}};
 if(failed.length)console.error('[FWW QA] integrity failures',failed);else console.info(`[FWW QA] ${results.length}/${results.length} integrity checks passed`);
})();