(()=>{
 const errors=[],warnings=[];const check=(ok,msg,level='error')=>{if(!ok)(level==='warning'?warnings:errors).push(msg)};const ids=a=>new Set((a||[]).map(x=>x.id));
 try{
  check(!!window.AppRouter,'AppRouter missing');check(!!window.AppState,'AppState missing');
  const required=['home','train','move','progress','learn','curriculum','whipcurriculum','whiptrain','whipmove','weapon','weaponlesson','weaponlibrary','weapontech','adaptivelab','offenselibrary','combolab','fitness','fitnessworkout','readiness','program','completeprogram','instruction','passport'];required.forEach(r=>check(AppRouter.has(r),`Route missing: ${r}`));
  check(state.readiness&&typeof state.readiness==='object'&&!Array.isArray(state.readiness),'Physical readiness profile invalid');check([null,'good','limited','pain'].includes(state.precheckStatus),'Precheck status invalid');
  const moveIds=ids(allMoves);(FLUID.sessions||[]).forEach(s=>(s.moves||[]).forEach(id=>check(moveIds.has(id),`FLUID ${s.id} references missing move ${id}`)));const whipIds=new Set(Object.keys(WHIP.drills||{}));(WHIP.sessions||[]).forEach(s=>(s.moves||[]).forEach(id=>check(whipIds.has(id),`WHIP ${s.id} references missing drill ${id}`)));
  const fluidComp=new Set(Object.keys(FLUID.competencies||{}));(FLUID.levels||[]).forEach(l=>(l.gate||[]).forEach(id=>check(fluidComp.has(id),`FLUID ${l.id} gate references missing competency ${id}`)));const whipComp=new Set(Object.keys(WHIP.competencies||{}));(WHIP.levels||[]).forEach(l=>(l.gate||[]).forEach(id=>check(whipComp.has(id),`WHIP ${l.id} gate references missing competency ${id}`)));const weaponComp=new Set(Object.keys(WEAPON.competencies||{}));(WEAPON.sessions||[]).forEach(s=>(s.skills||[]).forEach(id=>check(weaponComp.has(id),`WEAPON ${s.id} references missing competency ${id}`)));
  check(!!window.FWW_COMPREHENSIVE,'24-week curriculum missing');check(FWW_COMPREHENSIVE?.phases?.length===6,'Expected six 4-week comprehensive phases');check(typeof FWW_COMPREHENSIVE?.buildWeek==='function','Week builder missing');
  check(!!window.FWW_WORKOUTS,'Workout prescriptions missing');check(Object.keys(FWW_WORKOUTS?.sessions||{}).length>=8,'Comprehensive workout sessions incomplete');
  check(!!window.FWW_MOBILITY_CHAIN,'Mobility chain missing');check(FWW_MOBILITY_CHAIN?.levels?.length===4,'Mobility chain progression incomplete');check(!!window.FWW_BODY_DEVELOPMENT,'Body development missing');check(!!window.FWW_RANGE_CURRICULUM,'Range curriculum missing');check(Object.keys(FWW_RANGE_CURRICULUM?.ranges||{}).length===6,'R0–R5 range map incomplete');
  check(!!window.FWW_FLOW_TRAINING,'Flow training missing');check(FWW_FLOW_TRAINING?.vocabulary?.length>=10,'Flow vocabulary incomplete');check(!!window.FWW_ASSESSMENTS,'Assessment system missing');check(FWW_ASSESSMENTS?.domains?.length>=8,'Assessment domains incomplete');check(!!window.FWW_PASSPORT,'Movement Passport engine missing');
  check(!!window.FWW_INSTRUCTION_CARDS,'Instruction cards missing');const cards=FWW_INSTRUCTION_CARDS?.cards||[];check(cards.length>=30,`Instruction library thin: ${cards.length} cards`,'warning');const cardIds=ids(cards);check(cardIds.size===cards.length,'Duplicate instruction-card IDs');cards.forEach(c=>{check(c.frames?.length>=4,`${c.id} needs at least four visual frames`);check(c.how?.length>=4,`${c.id} execution steps incomplete`);check(c.cues?.length>=3,`${c.id} cues incomplete`);check(c.errors?.length>=3,`${c.id} error coaching incomplete`)});
  check(!!window.FWW_VISUAL_PRODUCTION,'Visual production contract missing');check(!!window.FWW_VISUAL_RENDERER,'Visual renderer missing');const va=FWW_VISUAL_RENDERER?.audit?.();if(va){check(va.total===cards.length,'Visual manifest/card count mismatch');check(va.approved===cards.length,`Final anatomical visuals incomplete: ${va.approved}/${va.total} approved`,'warning')}
  check(typeof finishSession==='function','FLUID completion missing');check(typeof finishWhipSession==='function','WHIP completion missing');check(typeof completeWeaponLesson==='function','WEAPON completion missing');check(typeof launchProgramBlock==='function','Program launcher missing');check(typeof weaponUnlocked==='function','WEAPON unlock missing');check(typeof whipUnlocked==='function','WHIP unlock missing');check(typeof renderComprehensiveProgram==='function','Complete program UI missing');check(typeof renderInstructionLibrary==='function','Instruction library UI missing');check(typeof renderPassportV11==='function','Passport UI missing');
 }catch(e){errors.push(`QA exception: ${e.message}`)}
 window.RUNTIME_QA={ok:errors.length===0,errors,warnings,run:()=>({ok:errors.length===0,errors:[...errors],warnings:[...warnings]})};if(errors.length)console.error('[FWW QA]',errors);else console.info('[FWW QA] comprehensive structural checks passed',warnings);
})();